### ISSUE TITLE
Grouping the Glossary into sections related to each other, including cross-linking

### ISSUE THREAD

**Issue by scycer** [hemanth/functional-programming-jargon#152]
I saw the issue alphabetical grouping and I understand why it is in it's current order but I feel this ordering could be even further improved. 

It took me a while to click that there is a matrix between the algebraic structures / type classes (functor, monad etc) and the types that's apply those structures (maybe, list, Task, future etc). I may be using the wrong terms but I think a good reference of this is the table on the [Ramda Fantasy](https://github.com/ramda/ramda-fantasy) site.

So if we could group the glossary by maybe:

- General Terms
- Algebraic structures
- Types that apply those structures?

Or something of the sort, as at the moment I can't quite get a clear order from the glossary even though I do have a decent understanding of each topic. Cross-linking would also be helpful to pull together idea, like Option and chain or map etc. Happy to help with adding more to this page, I think it could definitely be expanded into a github page, that may make it easier for people who want alphabetized terms or easy searching.

**Comment by jethrolarson** [comment]
I like this idea. Though it's a little tricky to categorize some of these terms since they exist in overlapping spheres. If we went hard into category theory classifications then maybe some structure would fall out but that might be more off-putting in some ways.

I would actually be interested in converting this to a more designed website so we can take advantage of some features like tagging and search and such but that would be a big undertaking and would not be without some loss.

The simplicity of this document I think has helped people contribute and add translations so maybe I better not. Sorry for rambling here. :)

**Comment by scycer** [comment]
nah that makes sense to me :) I have started a separate project myself, using what's here for a bit of inspiration to try and get into more of a website guide. It's nothing yet but I hope to cover off at least all the parts here in a structured way to encourage people to learn FP. There are many good resources that I have found so far that cover off different parts but nothing end to end and interactive, in particular showing where to apply the FP style and how it compares to OO and Imperative [TeachMeFPinJS](https://github.com/scycer/TeachMeFPinJS)

**Comment by jethrolarson** [comment]
I don't think this is really actionabe at this point so I'm gonna close
